version: '3.4'

services:
  web:
    image: ramonagospodinova/web_impression:latest
    build: .
    command: gunicorn webImpression.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/tmp/webImpression/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.prod
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: web_impression_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web